import json
from pathlib import Path
ROOT = Path(__file__).parent
cur = json.loads((ROOT / "phrases.json").read_text(encoding="utf-8"))

NEW = [
["Me llamo…","My name is…","Basics"],
["¿Cómo te llamas?","What's your name?","Basics"],
["¿De dónde eres?","Where are you from?","Basics"],
["Hola","Hello","Basics"],
["Adiós","Goodbye","Basics"],
["Buenos días","Good morning","Basics"],
["Buenas tardes","Good afternoon","Basics"],
["Buenas noches","Good evening / Good night","Basics"],
["¿Cómo estás?","How are you?","Basics"],
["Estoy bien, gracias","I'm well, thanks","Basics"],
["¿Y tú?","And you?","Basics"],
["Sí","Yes","Basics"],
["No","No","Basics"],
["Por favor","Please","Basics"],
["Gracias","Thank you","Basics"],
["Muchas gracias","Thank you very much","Basics"],
["Lo siento","I'm sorry","Basics"],
["No hay problema","No problem","Basics"],
["Con gusto","My pleasure","Basics","MX"],
["No entiendo","I don't understand","Basics"],
["¿Hablas inglés?","Do you speak English?","Basics"],
["No hablo mucho español","I don't speak much Spanish","Basics"],
["¿Puede repetir, por favor?","Can you repeat, please?","Basics","formal"],
["¿Dónde está el baño?","Where is the bathroom?","Basics"],
["Tengo hambre","I'm hungry","Basics"],
["Tengo sed","I'm thirsty","Basics"],
["Estoy cansado","I'm tired","Basics","m"],
["Hace calor","It's hot","Basics"],
["Hace frío","It's cold","Basics"],
["¿Qué hora es?","What time is it?","Basics"],
["Son las dos","It's two o'clock","Basics"],
["Uno","One","Basics"],
["Dos","Two","Basics"],
["Tres","Three","Basics"],
["Cuatro","Four","Basics"],
["Cinco","Five","Basics"],
["Seis","Six","Basics"],
["Siete","Seven","Basics"],
["Ocho","Eight","Basics"],
["Nueve","Nine","Basics"],
["Diez","Ten","Basics"],
["Veinte","Twenty","Basics"],
["Cien","One hundred","Basics"],
["Mil","One thousand","Basics"],
["Lunes","Monday","Basics"],
["Martes","Tuesday","Basics"],
["Miércoles","Wednesday","Basics"],
["Jueves","Thursday","Basics"],
["Viernes","Friday","Basics"],
["Sábado","Saturday","Basics"],
["Domingo","Sunday","Basics"],
["Ayer","Yesterday","Basics"],

["Estoy perdido","I'm lost","Out & about","m"],
["¿Cómo llego a…?","How do I get to…?","Out & about"],
["A la derecha","To the right","Out & about"],
["A la izquierda","To the left","Out & about"],
["Todo recto","Straight ahead","Out & about"],
["¿Está abierto?","Is it open?","Out & about"],
["¿A qué hora cierran?","What time do you close?","Out & about"],
["Quisiera…","I would like…","Out & about","polite"],
["La cuenta, por favor","The bill, please","Out & about"],
["¿Tiene wifi?","Do you have wifi?","Out & about"],
["¿Cuál es la contraseña?","What's the password?","Out & about"],
["Un café, por favor","A coffee, please","Out & about"],
["Una cerveza, por favor","A beer, please","Out & about"],
["Agua, por favor","Water, please","Out & about"],
["Estoy buscando…","I'm looking for…","Out & about"],
["¿Puedo pagar con tarjeta?","Can I pay by card?","Out & about"],
["¿Dónde puedo tomar un taxi?","Where can I get a taxi?","Out & about"],
["¿Me recomienda algo?","Can you recommend something?","Out & about","formal"],
["Está delicioso","It's delicious","Social"],
["Estoy lleno","I'm full","Social","m"],
["Quédate con el cambio","Keep the change","Out & about"],
["Disculpe","Excuse me","Out & about","formal"],
["¡Felicidades!","Congratulations!","Social"],
["¡Buen fin de semana!","Have a good weekend!","Social"],

["Mucho gusto en conocerte","Nice to meet you","Networking"],
["Encantado de conocerte","Pleased to meet you","Networking","m"],
["Encantada de conocerte","Pleased to meet you","Networking","f"],
["¿De qué empresa eres?","What company are you with?","Networking"],
["Tengo mi propia empresa","I have my own company","Networking"],
["Me dedico a las ventas","I work in sales","Networking"],
["¿Tienes una tarjeta de presentación?","Do you have a business card?","Networking"],
["Aquí tienes mi tarjeta","Here's my card","Networking"],
["¿Nos conectamos en LinkedIn?","Shall we connect on LinkedIn?","Networking"],
["¿Me pasas tu número?","Can I get your number?","Networking"],
["¿Cuál es tu correo?","What's your email?","Networking"],
["Te escribo esta semana","I'll write to you this week","Networking"],
["Mantengamos el contacto","Let's keep in touch","Networking"],
["¿Qué te trae por aquí?","What brings you here?","Networking"],
["¿Es tu primera vez en este evento?","Is this your first time at this event?","Networking"],
["¿Podemos agendar una reunión?","Can we schedule a meeting?","Networking"],
["¿Tienes un minuto?","Do you have a minute?","Networking"],
["Déjame presentarte a…","Let me introduce you to…","Networking"],
["Ella es mi colega","She is my colleague","Networking"],
["Él es mi socio","He is my business partner","Networking"],
["¿En qué puedo ayudarte?","How can I help you?","Networking"],
["Cuéntame más","Tell me more","Networking"],
["Suena interesante","That sounds interesting","Networking"],
["Me encantaría colaborar","I'd love to collaborate","Networking"],
["Hablemos pronto","Let's talk soon","Networking"],
["Te mando la información","I'll send you the info","Networking"],
["¿Me recomiendas a alguien?","Can you recommend someone?","Networking"],
["Estoy buscando clientes","I'm looking for clients","Networking"],
["¿Buscas proveedores?","Are you looking for suppliers?","Networking"],
["Trabajemos juntos","Let's work together","Networking"],
["Fue un gusto","It was a pleasure","Networking"],
["Seguimos en contacto","We'll stay in touch","Networking"],
["¿Vienes seguido a estos eventos?","Do you come to these events often?","Networking"],
["¿Me presentas?","Can you introduce me?","Networking"],
["Tengo una propuesta para ti","I have a proposal for you","Networking"],
["¿Cuándo te viene bien?","When works for you?","Networking"],
["Gracias por tu tiempo","Thanks for your time","Networking"],
["Quedo a tus órdenes","I'm at your service","Networking","MX"],
["¿Cómo va el negocio?","How's business?","Networking"],

["¿Estás soltero?","Are you single?","Dating","to a man"],
["¿Estás soltera?","Are you single?","Dating","to a woman"],
["¿Tienes novio?","Do you have a boyfriend?","Dating"],
["¿Tienes novia?","Do you have a girlfriend?","Dating"],
["Me gustas","I like you","Dating"],
["Eres muy guapo","You're very handsome","Dating"],
["Eres muy guapa","You're very pretty","Dating"],
["Tienes una sonrisa bonita","You have a nice smile","Dating"],
["¿Quieres salir conmigo?","Do you want to go out with me?","Dating"],
["¿Te gustaría tomar un café?","Would you like to get a coffee?","Dating"],
["¿Puedo invitarte una copa?","Can I buy you a drink?","Dating"],
["¿Me das tu número?","Can I have your number?","Dating"],
["¿Nos vemos otra vez?","Can we see each other again?","Dating"],
["La pasé muy bien","I had a great time","Dating"],
["Me encantó conocerte","I loved meeting you","Dating"],
["Pienso en ti","I'm thinking about you","Dating"],
["Me haces feliz","You make me happy","Dating"],
["Cuéntame de ti","Tell me about yourself","Dating"],
["¿Qué te gusta hacer?","What do you like to do?","Dating"],
["¿Cuáles son tus pasatiempos?","What are your hobbies?","Dating"],
["Tenemos mucho en común","We have a lot in common","Dating"],
["Me siento cómodo contigo","I feel comfortable with you","Dating","m"],
["Busco algo serio","I'm looking for something serious","Dating"],
["No busco nada casual","I'm not looking for anything casual","Dating"],
["Quiero formar una familia","I want to start a family","Dating"],
["¿Qué buscas en una pareja?","What do you look for in a partner?","Dating"],
["Eres especial para mí","You're special to me","Dating"],
["Me gustaría conocerte mejor","I'd like to get to know you better","Dating"],
["Me gusta pasar tiempo contigo","I like spending time with you","Dating"],
["Eres increíble","You're amazing","Dating"],
["Me encanta tu forma de ser","I love the way you are","Dating"],
["¿Quieres ser mi pareja?","Do you want to be my partner?","Dating"],
["Te extraño","I miss you","Dating"],
["¿Cuándo te vuelvo a ver?","When will I see you again?","Dating"],
["¿Vives solo?","Do you live alone?","Dating","to a man"],
["¿Vives sola?","Do you live alone?","Dating","to a woman"],
["¿Qué tipo de música te gusta?","What kind of music do you like?","Dating"],
["¿Te gusta viajar?","Do you like to travel?","Dating"],
["Hacemos buena pareja","We make a good couple","Dating"],
["¿Crees en el destino?","Do you believe in fate?","Dating"],

["Energía solar","Solar energy","Solar"],
["Paneles solares","Solar panels","Solar"],
["Instalamos paneles solares","We install solar panels","Solar"],
["¿Cuánto cuesta la instalación?","How much is the installation?","Solar"],
["Te ahorra dinero","It saves you money","Solar"],
["Reduce tu recibo de luz","It lowers your electricity bill","Solar"],
["¿Cuánto pagas de luz al mes?","How much do you pay for electricity a month?","Solar"],
["El inversor","The inverter","Solar"],
["La batería","The battery","Solar"],
["El techo","The roof","Solar"],
["¿Tu techo recibe sol?","Does your roof get sun?","Solar"],
["¿Cuántos paneles necesito?","How many panels do I need?","Solar"],
["Hacemos una cotización gratis","We do a free quote","Solar"],
["Te mando la cotización hoy","I'll send you the quote today","Solar"],
["¿Cuánto dura la instalación?","How long does the installation take?","Solar"],
["Tenemos garantía de 25 años","We have a 25-year warranty","Solar"],
["Se paga solo en pocos años","It pays for itself in a few years","Solar"],
["La energía es limpia","The energy is clean","Solar"],
["Es bueno para el medio ambiente","It's good for the environment","Solar"],
["Funciona con la luz del sol","It works with sunlight","Solar"],
["¿Cuánto genera al día?","How much does it generate per day?","Solar"],
["Medición neta","Net metering","Solar"],
["Conectamos a la red","We connect to the grid","Solar"],
["Ofrecemos financiamiento","We offer financing","Solar"],
["¿Te interesa ahorrar en luz?","Are you interested in saving on electricity?","Solar"],
["Podemos agendar una visita","We can schedule a visit","Solar"],
["Hacemos el mantenimiento","We do the maintenance","Solar"],
["¿Cuál es tu consumo?","What's your consumption?","Solar"],
["La inversión vale la pena","The investment is worth it","Solar"],
["Trabajamos con empresas y casas","We work with businesses and homes","Solar"],
["¿Es tu casa o rentas?","Is it your house or do you rent?","Solar"],
["Necesito ver tu recibo","I need to see your bill","Solar"],
["Te explico cómo funciona","Let me explain how it works","Solar"],
["No necesitas pagar por adelantado","You don't need to pay upfront","Solar"],
["El sol es gratis","The sun is free","Solar"],
["Cuida el planeta","It takes care of the planet","Solar"],
["¿Cuándo quieres empezar?","When do you want to start?","Solar"],
["Trabajo en energía solar","I work in solar energy","Solar"],
["¿Cuánto espacio hay en tu techo?","How much space is on your roof?","Solar"],
["Más energía, menos costo","More energy, less cost","Solar"],
["Vendemos e instalamos","We sell and install","Solar"],
["Un momento, por favor","One moment, please","Basics"],
["Nos vemos pronto","See you soon","Social"],
["¿Cómo se llama esto?","What is this called?","Understanding"],
["Estoy aprendiendo español","I'm learning Spanish","Basics"],
["¿Me ayudas con esto?","Can you help me with this?","Networking"],
["¿Tienes planes esta noche?","Do you have plans tonight?","Dating"],
["¿Te gusta bailar?","Do you like to dance?","Dating"],
["¿Puedes darme un ejemplo?","Can you give me an example?","Understanding"],
]

existing = {e[0] for e in cur}
seen, add = set(), []
for e in NEW:
    if e[0] in existing or e[0] in seen:
        print("skip dup:", e[0]); continue
    seen.add(e[0]); add.append(e)
print("unique new:", len(add))
assert len(add) >= 200, f"need >=200, have {len(add)}"
add = add[:200]
allp = cur + add
text = "[\n" + ",\n".join(json.dumps(e, ensure_ascii=False) for e in allp) + "\n]\n"
(ROOT / "phrases.json").write_text(text, encoding="utf-8")
print("total phrases:", len(allp))
